"""SQLAlchemy database models for nav fee service."""

from sqlalchemy import Column, String, Float, Integer, Boolean, Text, DateTime, ForeignKey, JSON
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime

Base = declarative_base()


class ANSProviderModel(Base):
    """ANS provider database model."""
    
    __tablename__ = "ans_providers"
    
    id = Column(Integer, primary_key=True)
    icao_code = Column(String(10), unique=True, nullable=False, index=True)
    name = Column(String(255), nullable=False)
    country = Column(String(100), nullable=False)
    
    # Fee formula
    fee_formula_type = Column(String(50), nullable=False)  # flat, mtow, distance, etc.
    base_unit_rate = Column(Float, nullable=False)
    
    # Special rules
    applies_50km_deduction = Column(Boolean, default=False)
    minimum_distance_nm = Column(Float, default=0.0)
    vat_rate = Column(Float, default=0.0)
    
    currency = Column(String(3), default="USD")
    
    # Metadata
    notes = Column(Text)
    managed_firs = Column(JSON)  # Array of FIR codes
    last_updated = Column(DateTime, default=datetime.utcnow)
    
    # Versioning
    data_version = Column(String(20), default="1.0")
    
    def __repr__(self):
        return f"<ANSProvider {self.icao_code} - {self.name}>"


class FIRModel(Base):
    """Flight Information Region database model."""
    
    __tablename__ = "firs"
    
    id = Column(Integer, primary_key=True)
    icao_code = Column(String(10), unique=True, nullable=False, index=True)
    name = Column(String(255), nullable=False)
    country = Column(String(100), nullable=False)
    
    # ANS provider
    ans_provider = Column(String(10), ForeignKey("ans_providers.icao_code"))
    
    # Geographic
    region = Column(String(50), index=True)  # AFRICA, EUROPE, ASIA, etc.
    boundary_geojson = Column(JSON)  # GeoJSON polygon
    
    min_altitude_ft = Column(Integer, default=0)
    max_altitude_ft = Column(Integer, default=65000)
    
    notes = Column(Text)
    last_updated = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<FIR {self.icao_code} - {self.name}>"


class FeeCalculationLog(Base):
    """Audit log for fee calculations."""
    
    __tablename__ = "fee_calculation_logs"
    
    id = Column(Integer, primary_key=True)
    request_id = Column(String(100), index=True)
    
    # Aircraft
    aircraft_icao_type = Column(String(20))
    aircraft_mtow_kg = Column(Float)
    
    # Route
    origin_icao = Column(String(10))
    destination_icao = Column(String(10))
    route_waypoints = Column(JSON)
    
    # FIRs crossed
    firs_crossed = Column(JSON)
    total_distance_nm = Column(Float)
    
    # Results
    total_fee_usd = Column(Float)
    fee_breakdown = Column(JSON)
    
    # Metadata
    calculation_method = Column(String(50))  # standard, wind_optimized, etc.
    api_version = Column(String(20))
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    
    def __repr__(self):
        return f"<FeeLog {self.request_id}>"


class PermitQuote(Base):
    """Aviation permit fee quotes generated by Jetelio."""
    
    __tablename__ = "permit_quotes"
    
    id = Column(Integer, primary_key=True)
    permit_id = Column(String(50), unique=True, nullable=False, index=True)
    operator_id = Column(String(100), index=True)
    
    # Flight details
    aircraft_reg = Column(String(20))
    aircraft_icao_type = Column(String(20))
    aircraft_mtow_kg = Column(Float)
    
    # Route
    origin_icao = Column(String(10))
    destination_icao = Column(String(10))
    route_waypoints = Column(JSON)
    
    # Fee breakdown
    navigation_fee_usd = Column(Float)
    jetelio_margin_usd = Column(Float)
    total_quote_usd = Column(Float)
    
    # Status
    is_accepted = Column(Boolean, default=False)
    quote_valid_until = Column(DateTime)
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def __repr__(self):
        return f"<PermitQuote {self.permit_id}>"
