export default () => ({
  app: {
    name: process.env.APP_NAME || 'Pounds Microfinance Ltd',
    port: parseInt(process.env.APP_PORT || '3001', 10),
    url: process.env.APP_URL || 'http://localhost:3000',
    frontendUrl: process.env.FRONTEND_URL || 'http://localhost:3000',
    env: process.env.NODE_ENV || 'development',
  },
  security: {
    jwtSecret: process.env.JWT_SECRET,
    jwtRefreshSecret: process.env.JWT_REFRESH_SECRET,
    jwtExpiresIn: process.env.JWT_EXPIRES_IN || '15m',
    jwtRefreshExpiresIn: process.env.JWT_REFRESH_EXPIRES_IN || '7d',
    sessionInactivityTimeout: parseInt(process.env.SESSION_INACTIVITY_TIMEOUT || '900', 10),
    encryptionKey: process.env.ENCRYPTION_KEY,
  },
  database: {
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '5432', 10),
    username: process.env.DB_USERNAME || 'pounds_user',
    password: process.env.DB_PASSWORD,
    name: process.env.DB_NAME || 'pounds_mfi',
    sync: process.env.DB_SYNC === 'true',
    logging: process.env.DB_LOGGING === 'true',
  },
  redis: {
    host: process.env.REDIS_HOST || 'localhost',
    port: parseInt(process.env.REDIS_PORT || '6379', 10),
    password: process.env.REDIS_PASSWORD,
    db: parseInt(process.env.REDIS_DB || '0', 10),
  },
  storage: {
    type: process.env.STORAGE_TYPE || 'local',
    localPath: process.env.STORAGE_LOCAL_PATH || '/app/uploads',
    maxFileSize: parseInt(process.env.STORAGE_MAX_FILE_SIZE || '10485760', 10),
    s3: {
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
      region: process.env.AWS_REGION || 'us-east-1',
      bucket: process.env.AWS_S3_BUCKET,
    },
  },
  email: {
    host: process.env.SMTP_HOST,
    port: parseInt(process.env.SMTP_PORT || '587', 10),
    secure: process.env.SMTP_SECURE === 'true',
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
    from: process.env.SMTP_FROM,
  },
  sms: {
    provider: process.env.SMS_PROVIDER || 'africastalking',
    at: {
      apiKey: process.env.AT_API_KEY,
      username: process.env.AT_USERNAME || 'sandbox',
      senderId: process.env.AT_SENDER_ID || 'POUNDS',
    },
    twilio: {
      accountSid: process.env.TWILIO_ACCOUNT_SID,
      authToken: process.env.TWILIO_AUTH_TOKEN,
      fromNumber: process.env.TWILIO_FROM_NUMBER,
    },
  },
  whatsapp: {
    provider: process.env.WHATSAPP_PROVIDER || '360dialog',
    apiKey: process.env.WHATSAPP_API_KEY,
    apiUrl: process.env.WHATSAPP_API_URL,
    fromNumber: process.env.WHATSAPP_FROM_NUMBER,
  },
  ocr: {
    lang: process.env.TESSERACT_LANG || 'eng',
    dataPath: process.env.TESSERACT_DATA_PATH || '/usr/share/tesseract-ocr/4.00/tessdata',
  },
  financial: {
    processingFeePercent: parseFloat(process.env.DEFAULT_PROCESSING_FEE_PERCENT || '5'),
    penaltyPercent: parseFloat(process.env.DEFAULT_PENALTY_PERCENT || '5'),
    penaltyFrequency: process.env.DEFAULT_PENALTY_FREQUENCY || 'weekly',
  },
  backup: {
    enabled: process.env.BACKUP_ENABLED === 'true',
    schedule: process.env.BACKUP_SCHEDULE || '0 2 * * *',
    retentionDays: parseInt(process.env.BACKUP_RETENTION_DAYS || '30', 10),
    emailRecipients: (process.env.BACKUP_EMAIL_RECIPIENTS || '').split(',').filter(Boolean),
    sftp: {
      host: process.env.SFTP_HOST,
      port: parseInt(process.env.SFTP_PORT || '22', 10),
      user: process.env.SFTP_USER,
      keyPath: process.env.SFTP_KEY_PATH,
      remotePath: process.env.SFTP_REMOTE_PATH || '/backups',
    },
  },
  branding: {
    name: process.env.BRAND_NAME || 'Pounds Microfinance Ltd',
    tagline: process.env.BRAND_TAGLINE || 'Financial Empowerment for All',
    primaryColor: process.env.BRAND_PRIMARY_COLOR || '#1E40AF',
    secondaryColor: process.env.BRAND_SECONDARY_COLOR || '#059669',
    logoUrl: process.env.BRAND_LOGO_URL || '/assets/logo.png',
    faviconUrl: process.env.BRAND_FAVICON_URL || '/assets/favicon.ico',
    footerText: process.env.BRAND_FOOTER_TEXT || '© 2024 Pounds Microfinance Ltd.',
    supportEmail: process.env.BRAND_SUPPORT_EMAIL,
    supportPhone: process.env.BRAND_SUPPORT_PHONE,
  },
  rateLimit: {
    ttl: parseInt(process.env.RATE_LIMIT_TTL || '60', 10),
    max: parseInt(process.env.RATE_LIMIT_MAX || '100', 10),
  },
});
